### ISSUE TITLE
interface mounted: false whereas the interface is up

### ISSUE THREAD

**Issue by deadlybore** [grid5000/g5k-checks#9]
When generating a yaml with `g5k-checks -m api` on chinqchint-1 we get this: 

``` yaml

---
architecture:
  smp_size: 2
  smt_size: 8
  platform_type: x86_64
bios:
  vendor: Phoenix Technologies LTD
  version: 6.0
  release_date: 09/10/2007
chassis:
  serial_number: X0004740
  manufacturer: SGI.COM
  product_name: AltixXE310
block_devices:
  sda:
    device: sda
    size: 250059350016
    model: Hitachi HDT72502
    rev: A7EA
supported_job_types:
  virtual: ivt
main_memory:
  ram_size: 8391753728
network_interfaces:
  eth0:
    interface: Ethernet
    ip6: fe80::230:48ff:fe7c:7c86
    driver: e1000e
    mac: 00:30:48:7c:7c:86
    rate: 1000000000
    mounted: false
    management: false
  eth1:
    interface: Ethernet
    ip: 172.16.34.1
    driver: e1000e
    mac: 00:30:48:7c:7c:87
    rate: 1000000000
    mounted: true
    management: false
```

We can see that we got `mounted: false` for the eth0 interface though this interface is up (but with no IP):

```
$ ip link show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 00:30:48:7c:7c:86 brd ff:ff:ff:ff:ff:ff
```
